# Generated by Django 5.0.1 on 2024-01-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='position',
        ),
    ]
