# Generated by Django 5.0.1 on 2024-02-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
