# Generated by Django 5.0.1 on 2024-02-05 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_board_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='board', to=settings.AUTH_USER_MODEL),
        ),
    ]
