export const colors = [
    { theme: "black", color_text: "green_muted", color: "#164B35", text_color: "#BAF3DB", text: "приглушенный зеленый" },
    { theme: "black", color_text: "yellow_muted", color: "#533F04", text_color: "#F8E6A0", text: "приглушенный желтый" },
    { theme: "black", color_text: "orange_muted", color: "#702E00", text_color: "#FEDEC8", text: "приглушенный оранжевый" },
    { theme: "black", color_text: "red_muted", color: "#5D1F1A", text_color: "#FFD5D2", text: "приглушенный красный" },
    { theme: "black", color_text: "violet_muted", color: "#352C63", text_color: "#DFD8FD", text: "приглушенный фиолетовый" },
    { theme: "black", color_text: "green", color: "#216E4E", text_color: "#BAF3DB", text: "зеленый" },
    { theme: "black", color_text: "yellow", color: "#7F5F01", text_color: "#F8E6A0", text: "желтый" },
    { theme: "black", color_text: "orange", color: "#A54800", text_color: "#FEDEC8", text: "оранжевый" },
    { theme: "black", color_text: "red", color: "#AE2E24", text_color: "#FFD5D2", text: "красный" },
    { theme: "black", color_text: "violet", color: "#5E4DB2", text_color: "#DFD8FD", text: "фиолетовый" },
    { theme: "black", color_text: "green_intense", color: "#4BCE97", text_color: "#1D2125", text: "ярко-зеленый" },
    { theme: "black", color_text: "yellow_intense", color: "#E2B203", text_color: "#1D2125", text: "ярко-желтый" },
    { theme: "black", color_text: "orange_intense", color: "#FEDEC8", text_color: "#702E00", text: "ярко-оранжевый" },
    { theme: "black", color_text: "red_intense", color: "#F87168", text_color: "#1D2125", text: "ярко-красный" },
    { theme: "black", color_text: "violet_intense", color: "#9F8FEF", text_color: "#1D2125", text: "ярко-фиолетовый" },
    { theme: "black", color_text: "blue_muted", color: "#09326C", text_color: "#CCE0FF", text: "приглушенный синий" },
    { theme: "black", color_text: "cyan_muted", color: "#164555", text_color: "#C6EDFB", text: "приглушенный голубой" },
    { theme: "black", color_text: "lime_muted", color: "#37471F", text_color: "#D3F1A7", text: "приглушенный лаймовый" },
    { theme: "black", color_text: "pink_muted", color: "#50253F", text_color: "#FDD0EC", text: "приглушенный розовый" },
    { theme: "black", color_text: "grey_muted", color: "#454F59", text_color: "#DEE4EA", text: "приглушенный серый" },
    { theme: "black", color_text: "blue", color: "#0055CC", text_color: "#CCE0FF", text: "синий" },
    { theme: "black", color_text: "cyan", color: "#206A83", text_color: "#C6EDFB", text: "голубой" },
    { theme: "black", color_text: "lime", color: "#4C6B1F", text_color: "#D3F1A7", text: "лаймовый" },
    { theme: "black", color_text: "pink", color: "#943D73", text_color: "#FDD0EC", text: "розовый" },
    { theme: "black", color_text: "grey", color: "#596773", text_color: "#DEE4EA", text: "серый" },
    { theme: "black", color_text: "blue_intense", color: "#579DFF", text_color: "#1D2125", text: "ярко-синий" },
    { theme: "black", color_text: "cyan_intense", color: "#6CC3E0", text_color: "#1D2125", text: "ярко-голубой" },
    { theme: "black", color_text: "lime_intense", color: "#94C748", text_color: "#1D2125", text: "ярко-лаймовый" },
    { theme: "black", color_text: "pink_intense", color: "#E774BB", text_color: "#1D2125", text: "ярко-розовый" },
    { theme: "black", color_text: "grey_intense", color: "#8C9BAB", text_color: "#1D2125", text: "ярко-серый" },
]
